### ISSUE TITLE
Add table to lab2

### ISSUE THREAD

**Issue by vegro90** [sloydsalen/KJM1101-exercises#1]
# Suggestion
Since most students most likely arent used to seeing data in csv-format, would it be nice to add a table to visualise how the CSV-data would look in excel?
Here is an example markdown snippet: ( the latex code will format properly in Jupyter.)

## Fix

| "m_Zn / g" | "V_gass / mL" | "P_0 / mmHg" | "t / degC" | "h_vann / mm" |
|--- | --- | --- | --- | --- |
| 0.090 | 34.4 | 1.013 | 23.2 | 135 |
| 0.092 | 35.1 | 0.9926 | 22 | 133 |
| $$\vdots$$ | $$\vdots$$ | $$\vdots$$ | $$\vdots$$ | $$\vdots$$ |

**Comment by sverl** [comment]
Added table formatted in MathJax instead of markdown.
